#!/bin/bash

export server_dir="../../../lcrq-server/"
export servers="http-server msq lcrq-server"

function start_server () {
    $server = $1
    killall http-server msq lcrq-server
    export NTHREADS=$2
    $server_dir/$server 8888 ~/html &> /dev/null &
    export server_pid=$!
}
    
function report_n_threads () {
    test_name=$2
    if [[ -z $test_name ]]; then
	test_name=$RANDOM
    fi
    perf report --no-children -i $server-$NTHREADS-workers-$test_name
}

function start_report () {
    server=$1
    perf record -g -e cpu-clock,task-clock -p $server_pid \
	 -o $server-$NTHREADS-workers-$1 -- sleep 5
}
